version: '3.8'
services:
  app:
    build: .
    ports:
      - "8001:8001"
      - "2345:2345" # delveと通信するためのポート
    volumes:
      - ./app:/app
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
